### ISSUE TITLE
Packagist.org

### ISSUE THREAD

**Issue by snickom** [websupport-sk/api_php#2]
Bolo by mozno fajn, ak uz pouzivate instalaciu cez composer, aby ste zaregistrovat balicek na http://packagist.org/, potom instalacia by vyzerala len tak, ze by sa pridal riadok "websupport/api_php" : "*" do require a nemusi sa zbytocne pridavat aj odkaz na repozitar.

**Comment by tatarko** [comment]
S vacsim meskanim, ale predsa sme pridali podporu aj pre packagist. V ramci require ale odporucam pouzivat skor `~1.0` pre pripad, ze by sme sa rozhodli v buducnosti v tejto libke urobit razantnejsie zmeny.
